# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/node-9.6.31" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "9.6.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-9.6.31.tgz";
        sha512 = "kIVlvUBizL51ALNMPbmcZoM7quHyB7J6fLRwQe22JsMp39nrVSHdBeVVS3fnQCK1orxI3O8LScmb8cuiihkAfA==";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "applescript-1.0.0" = {
      name = "applescript";
      packageName = "applescript";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/applescript/-/applescript-1.0.0.tgz";
        sha1 = "bb87af568cad034a4e48c4bdaf6067a3a2701317";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "auto-launch-5.0.5" = {
      name = "auto-launch";
      packageName = "auto-launch";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/auto-launch/-/auto-launch-5.0.5.tgz";
        sha512 = "ppdF4mihhYzMYLuCcx9H/c5TUOCev8uM7en53zWVQhyYAJrurd2bFZx3qQVeJKF2jrc7rsPRNN5cD+i23l6PdA==";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.8.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.8.0.tgz";
        sha512 = "ReZxvNHIOv88FlT7rxcXIIC0fPt4KZqZbOlivyWtXLt8ESx84zd3kMC6iK5jVeS2qt+g7ftS7ye4fi06X5rtRQ==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "bignumber.js-2.4.0" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-2.4.0.tgz";
        sha1 = "838a992da9f9d737e0f4b2db0be62bb09dd0c5e8";
      };
    };
    "bmp-js-0.0.3" = {
      name = "bmp-js";
      packageName = "bmp-js";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bmp-js/-/bmp-js-0.0.3.tgz";
        sha1 = "64113e9c7cf1202b376ed607bf30626ebe57b18a";
      };
    };
    "buffer-equal-0.0.1" = {
      name = "buffer-equal";
      packageName = "buffer-equal";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal/-/buffer-equal-0.0.1.tgz";
        sha1 = "91bc74b11ea405bc916bc6aa908faafa5b4aac4b";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "dom-walk-0.1.1" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.1.tgz";
        sha1 = "672226dc74c8f799ad35307df936aba11acd6018";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "electron-window-state-4.1.1" = {
      name = "electron-window-state";
      packageName = "electron-window-state";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-window-state/-/electron-window-state-4.1.1.tgz";
        sha1 = "6b34fdc31b38514dfec8b7c8f7b5d4addb67632d";
      };
    };
    "es6-promise-3.3.1" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-3.3.1.tgz";
        sha1 = "a08cdde84ccdbf34d027a1451bc91d4bcd28a613";
      };
    };
    "exif-parser-0.1.12" = {
      name = "exif-parser";
      packageName = "exif-parser";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/exif-parser/-/exif-parser-0.1.12.tgz";
        sha1 = "58a9d2d72c02c1f6f02a0ef4a9166272b7760922";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "file-type-3.9.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "3.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-3.9.0.tgz";
        sha1 = "257a078384d1db8087bc449d107d52a52672b9e9";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "global-4.3.2" = {
      name = "global";
      packageName = "global";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.3.2.tgz";
        sha1 = "e76989268a6c74c38908b1305b10fc0e394e9d0f";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.0" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.0.tgz";
        sha512 = "+qnmNjI4OfH2ipQ9VQOw23bBd/ibtfbVdK2fYbY4acTDqKTW/YDp9McimZdDbG8iV9fZizUqQMD5xvriB146TA==";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "ip-regex-1.0.3" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-1.0.3.tgz";
        sha1 = "dc589076f659f419c222039a33316f1c7387effd";
      };
    };
    "is-callable-1.1.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.4.tgz";
        sha512 = "r5p9sxJjYnArLjObpjA4xu5EKI3CuKHkJXMhT7kwbpUyIFD1n5PMAsoPvWnvtZiNz7LjkYDRZhd7FlI0eMijEA==";
      };
    };
    "is-function-1.0.1" = {
      name = "is-function";
      packageName = "is-function";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-function/-/is-function-1.0.1.tgz";
        sha1 = "12cfb98b65b57dd3d193a3121f5f6e2f437602b5";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jimp-0.2.28" = {
      name = "jimp";
      packageName = "jimp";
      version = "0.2.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/jimp/-/jimp-0.2.28.tgz";
        sha1 = "dd529a937190f42957a7937d1acc3a7762996ea2";
      };
    };
    "jpeg-js-0.2.0" = {
      name = "jpeg-js";
      packageName = "jpeg-js";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jpeg-js/-/jpeg-js-0.2.0.tgz";
        sha1 = "53e448ec9d263e683266467e9442d2c5a2ef5482";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsonfile-2.4.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-2.4.0.tgz";
        sha1 = "3736a2b428b87bbda0cc83b53fa3d633a35c2ae8";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "load-bmfont-1.4.0" = {
      name = "load-bmfont";
      packageName = "load-bmfont";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-bmfont/-/load-bmfont-1.4.0.tgz";
        sha512 = "kT63aTAlNhZARowaNYcY29Fn/QYkc52M3l6V1ifRcPewg2lvUZDAj7R6dXjOL9D0sict76op3T5+odumDSF81g==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.36.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.36.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.36.0.tgz";
        sha512 = "L+xvyD9MkoYMXb1jAmzI/lWYAxAMCPvIBSWur0PZ5nOf5euahRLVqH//FKW9mWp2lkqUgYiXPgkzfMUFi4zVDw==";
      };
    };
    "mime-types-2.1.20" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.20.tgz";
        sha512 = "HrkrPaP9vGuWbLK1B1FfgAkbqNjIuy4eHlIYnFi7kamZyLLrGlo2mpcx0bBmNpKqBtYtAfGbodDddIgddSJC2A==";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "parse-bmfont-ascii-1.0.6" = {
      name = "parse-bmfont-ascii";
      packageName = "parse-bmfont-ascii";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-ascii/-/parse-bmfont-ascii-1.0.6.tgz";
        sha1 = "11ac3c3ff58f7c2020ab22769079108d4dfa0285";
      };
    };
    "parse-bmfont-binary-1.0.6" = {
      name = "parse-bmfont-binary";
      packageName = "parse-bmfont-binary";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-binary/-/parse-bmfont-binary-1.0.6.tgz";
        sha1 = "d038b476d3e9dd9db1e11a0b0e53a22792b69006";
      };
    };
    "parse-bmfont-xml-1.1.4" = {
      name = "parse-bmfont-xml";
      packageName = "parse-bmfont-xml";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-xml/-/parse-bmfont-xml-1.1.4.tgz";
        sha512 = "bjnliEOmGv3y1aMEfREMBJ9tfL3WR0i0CKPj61DnSLaoxWR3nLrsQrEbCId/8rF4NyRF0cCqisSVXyQYWM+mCQ==";
      };
    };
    "parse-headers-2.0.1" = {
      name = "parse-headers";
      packageName = "parse-headers";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-headers/-/parse-headers-2.0.1.tgz";
        sha1 = "6ae83a7aa25a9d9b700acc28698cd1f1ed7e9536";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "phin-2.9.1" = {
      name = "phin";
      packageName = "phin";
      version = "2.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/phin/-/phin-2.9.1.tgz";
        sha512 = "aRmHatimRP+73UipPJEK6AWHWjNcwssW6QmOpUcogYVgO8hbSi2Dv/yDWQKs/DmTjK3gCaf6CNsuYcIBWMnlVw==";
      };
    };
    "pixelmatch-4.0.2" = {
      name = "pixelmatch";
      packageName = "pixelmatch";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixelmatch/-/pixelmatch-4.0.2.tgz";
        sha1 = "8f47dcec5011b477b67db03c243bc1f3085e8854";
      };
    };
    "png-to-ico-1.0.7" = {
      name = "png-to-ico";
      packageName = "png-to-ico";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/png-to-ico/-/png-to-ico-1.0.7.tgz";
        sha512 = "heHiZjPFhVgLiuSG4C4wwKN9YPGLpPJvOfXRyI+cEJf0vPutjJ4XDaeI2f/hzTFs+2juihDw3pP8R5JtTuQTGg==";
      };
    };
    "pngjs-3.3.3" = {
      name = "pngjs";
      packageName = "pngjs";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pngjs/-/pngjs-3.3.3.tgz";
        sha512 = "1n3Z4p3IOxArEs1VRXnZ/RXdfEniAUS9jb68g58FIXMNkPJeZd+Qh4Uq7/e0LVxAQGos1eIUrqrt4FpjdnEd+Q==";
      };
    };
    "process-0.5.2" = {
      name = "process";
      packageName = "process";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.5.2.tgz";
        sha1 = "1638d8a8e34c2f440a91db95ab9aeb677fc185cf";
      };
    };
    "psl-1.1.29" = {
      name = "psl";
      packageName = "psl";
      version = "1.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.1.29.tgz";
        sha512 = "AeUmQ0oLN02flVHXWh9sSJF7mcdFq0ppid/JkErufc3hGIV/AMa8Fo9VgDo/cT2jFdOWoFvHp90qqBH54W+gjQ==";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "read-chunk-1.0.1" = {
      name = "read-chunk";
      packageName = "read-chunk";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-chunk/-/read-chunk-1.0.1.tgz";
        sha1 = "5f68cab307e663f19993527d9b589cace4661194";
      };
    };
    "request-2.88.0" = {
      name = "request";
      packageName = "request";
      version = "2.88.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.0.tgz";
        sha512 = "NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E+lHDAJzu7kLAkDeY08z2/A0hg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "sshpk-1.14.2" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.2.tgz";
        sha1 = "c6fc61648a3d9c4e764fd3fcdf4ea105e492ba98";
      };
    };
    "stream-to-0.2.2" = {
      name = "stream-to";
      packageName = "stream-to";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to/-/stream-to-0.2.2.tgz";
        sha1 = "84306098d85fdb990b9fa300b1b3ccf55e8ef01d";
      };
    };
    "stream-to-buffer-0.1.0" = {
      name = "stream-to-buffer";
      packageName = "stream-to-buffer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-buffer/-/stream-to-buffer-0.1.0.tgz";
        sha1 = "26799d903ab2025c9bd550ac47171b00f8dd80a9";
      };
    };
    "tinycolor2-1.4.1" = {
      name = "tinycolor2";
      packageName = "tinycolor2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor2/-/tinycolor2-1.4.1.tgz";
        sha1 = "f4fad333447bc0b07d4dc8e9209d8f39a8ac77e8";
      };
    };
    "tough-cookie-2.4.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.4.3.tgz";
        sha512 = "Q5srk/4vDM54WJsJio3XNn6K2sCG+CQ8G5Wz6bZhRZoAe/+TxjWB/GlFAnYEbkYVlON9FMk/fE3h2RLpPXo4lQ==";
      };
    };
    "trim-0.0.1" = {
      name = "trim";
      packageName = "trim";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/trim/-/trim-0.0.1.tgz";
        sha1 = "5858547f6b290757ee95cccc666fb50084c460dd";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "untildify-3.0.3" = {
      name = "untildify";
      packageName = "untildify";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/untildify/-/untildify-3.0.3.tgz";
        sha512 = "iSk/J8efr8uPT/Z4eSUywnqyrQU7DSdMfdqK4iWEaUVVmcP5JcnpRqmVMwcwcnmI1ATFNgC5V90u09tBynNFKA==";
      };
    };
    "url-regex-3.2.0" = {
      name = "url-regex";
      packageName = "url-regex";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-regex/-/url-regex-3.2.0.tgz";
        sha1 = "dbad1e0c9e29e105dd0b1f09f6862f7fdb482724";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "winreg-1.2.4" = {
      name = "winreg";
      packageName = "winreg";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winreg/-/winreg-1.2.4.tgz";
        sha1 = "ba065629b7a925130e15779108cf540990e98d1b";
      };
    };
    "xhr-2.5.0" = {
      name = "xhr";
      packageName = "xhr";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr/-/xhr-2.5.0.tgz";
        sha512 = "4nlO/14t3BNUZRXIXfXe+3N6w3s1KoxcJUUURctd64BLRe67E4gRwp4PjywtDY72fXpZ1y6Ch0VZQRY/gMPzzQ==";
      };
    };
    "xml-parse-from-string-1.0.1" = {
      name = "xml-parse-from-string";
      packageName = "xml-parse-from-string";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml-parse-from-string/-/xml-parse-from-string-1.0.1.tgz";
        sha1 = "a9029e929d3dbcded169f3c6e28238d95a5d5a28";
      };
    };
    "xml2js-0.4.19" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.19.tgz";
        sha512 = "esZnJZJOiJR9wWKMyuvSE1y6Dq5LCuJanqhxslH2bxM6duahNZ+HMpCLhBQGZkbX6xRf8x1Y2eJlgt2q3qo49Q==";
      };
    };
    "xmlbuilder-9.0.7" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "9.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz";
        sha1 = "132ee63d2ec5565c557e20f4c22df9aca686b10d";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
in
{
  "riot-web-file:../riot-web/electron_app" = nodeEnv.buildNodePackage {
    name = "riot-web";
    packageName = "riot-web";
    version = "0.16.2";
    src = ../riot-web/electron_app;
    dependencies = [
      sources."@types/node-9.6.31"
      sources."ajv-5.5.2"
      sources."applescript-1.0.0"
      sources."asn1-0.2.4"
      sources."assert-plus-1.0.0"
      sources."asynckit-0.4.0"
      sources."auto-launch-5.0.5"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.8.0"
      sources."bcrypt-pbkdf-1.0.2"
      sources."bignumber.js-2.4.0"
      sources."bmp-js-0.0.3"
      sources."buffer-equal-0.0.1"
      sources."caseless-0.12.0"
      sources."co-4.6.0"
      sources."combined-stream-1.0.6"
      sources."core-util-is-1.0.2"
      sources."dashdash-1.14.1"
      sources."deep-equal-1.0.1"
      sources."delayed-stream-1.0.0"
      sources."dom-walk-0.1.1"
      sources."ecc-jsbn-0.1.2"
      sources."electron-window-state-4.1.1"
      sources."es6-promise-3.3.1"
      sources."exif-parser-0.1.12"
      sources."extend-3.0.2"
      sources."extsprintf-1.3.0"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."file-type-3.9.0"
      sources."for-each-0.3.3"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.2"
      sources."getpass-0.1.7"
      sources."global-4.3.2"
      sources."graceful-fs-4.1.11"
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.0"
      sources."http-signature-1.2.0"
      sources."ip-regex-1.0.3"
      sources."is-callable-1.1.4"
      sources."is-function-1.0.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jimp-0.2.28"
      sources."jpeg-js-0.2.0"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.3.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsonfile-2.4.0"
      sources."jsprim-1.4.1"
      sources."load-bmfont-1.4.0"
      sources."mime-1.6.0"
      sources."mime-db-1.36.0"
      sources."mime-types-2.1.20"
      sources."min-document-2.19.0"
      sources."minimist-1.2.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."oauth-sign-0.9.0"
      sources."parse-bmfont-ascii-1.0.6"
      sources."parse-bmfont-binary-1.0.6"
      sources."parse-bmfont-xml-1.1.4"
      sources."parse-headers-2.0.1"
      sources."path-is-absolute-1.0.1"
      sources."performance-now-2.1.0"
      sources."phin-2.9.1"
      sources."pixelmatch-4.0.2"
      sources."png-to-ico-1.0.7"
      sources."pngjs-3.3.3"
      sources."process-0.5.2"
      sources."psl-1.1.29"
      sources."punycode-1.4.1"
      sources."qs-6.5.2"
      sources."read-chunk-1.0.1"
      sources."request-2.88.0"
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."sshpk-1.14.2"
      sources."stream-to-0.2.2"
      sources."stream-to-buffer-0.1.0"
      sources."tinycolor2-1.4.1"
      sources."tough-cookie-2.4.3"
      sources."trim-0.0.1"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."untildify-3.0.3"
      sources."url-regex-3.2.0"
      sources."uuid-3.3.2"
      sources."verror-1.10.0"
      sources."winreg-1.2.4"
      sources."xhr-2.5.0"
      sources."xml-parse-from-string-1.0.1"
      sources."xml2js-0.4.19"
      sources."xmlbuilder-9.0.7"
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A feature-rich client for Matrix.org";
    };
    production = false;
    bypassCache = true;
  };
}